apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: java-spring-boot
spec:
  git:
    url: https://github.com/jmconelogin/spring-sql-jpa-cvs/
    ref:
      branch: main
